[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-req=ext-zip"
]

[phases.setup]
cmds = [
  "php artisan config:cache || true",
  "php artisan route:cache || true",
  "php artisan migrate --force || true"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"

